name: Update README

on:
  push:
    branches:
      - main  # Change if your main branch is named differently

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest version

      - name: Run script to update experience
        run: |
          python your_script.py  # Replace with your script name

      - name: Update README
        run: |
          echo "## Experience" >> README.md
          cat years_of_experience.txt >> README.md
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "Update years of experience"
          git push
