name: Update README

on:
  push:
    branches:
      - main  # Change if your main branch is named differently
  schedule:
    - cron: "0 0 * * *"  # This runs once a day (midnight UTC)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest version

      - name: Run script to update experience
        run: |
          python YOECalculator.py  # Replace with your script name

      - name: Commit changes
        run: |
          git config --local user.name "Elanchezhiyan P"
          git config --local user.email "elanche97@hotmail.com"
          git add README.md
          git commit -m "Update years of experience" || echo "No changes to commit"
          git push
